### PR TITLE
Add L1 and L2 fit notebook

### PR DESCRIPTION
**Pull request by dmadeka**
Introduces a dependency on bqplot and ipywidgets>=6.0.0 for the Notebook

### CODE REVIEW

**Comment by dmadeka** [comment]
@davidrosenberg Another one that may be useful is:

https://github.com/dmadeka/SciPy2017/blob/master/3%20-%20Dashboard%20for%20Training%20Neutral%20Networks.ipynb

Depends on this dataset:

https://www.kaggle.com/c/GiveMeSomeCredit

**Comment by davidrosenberg** [comment]
Great - thanks!

**Comment by dmadeka** [comment]
@davidrosenberg It's an older version from the last one I sent you, maybe we should iterate on this one?

**Comment by davidrosenberg** [comment]
Not sure I understand. You mean you committed an older version, but we should keep working on that one.  Or you want to replace with a newer version?

**Pull request merged**
